name: build-project
# run-name:
on:
  push:
    # Rien précisé donc tout

jobs:
  compile:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.19
    steps:
      - name: get-code
        uses: actions/checkout@v4

      - name: compile-project
        run: make