# Name of the workflow
name: Build project
# When triggered
on: push

jobs:
  # Job to compile the code
  compile:
    name: Compilation # Name printed in Github actions
    runs-on: ubuntu-latest # VM
    container:
      image: alpine:3.19 # Image of the VM

    steps:
      # Get code
      - uses: actions/checkout@v4

      # Missing packages installation
      - name: Packages installation
        # --no-cache limit memory utilization
        # build-base install the necessary packages (gcc, make, ...)
        run: apk add --no-cache build-base

      # Run `make` commande line
      - name: Compile project
        run: make