# Name of the workflow
name: Run tests
# When triggered
on: [push, pull_request]

jobs:
  # Job for the tests
  tests:
    name: Perform tests
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim

    steps:
      # Get code
      - uses: actions/checkout@v4

      # Missing packages installation
      - name: Packages installation
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential \
            check

      # Command line to run
      - name: Run tests
        run: make test

  # Job for the linter
  linter:
    name: Linter
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim

    steps:
      - uses: actions/checkout@v4
      - name: Packages installation
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential \
            check \
            clang-tidy

      - name: Run lint
        run: make lint

  # Job for the format check
  format-check:
    name: Checks code format
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim

    steps:
      - uses: actions/checkout@v4
      - name: Packages installation
        run: |
          apt-get update
          apt-get install -y --no-install-recommends make clang-format

      - name: Run format check
        run: make format-check

  # Job for the project coverage
  project-coverage:
    needs: tests
    name: Project coverage
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim

    steps:
      - uses: actions/checkout@v4
      - name: Package installation
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential \
            check \
            lcov
      
      - name: Run coverage
        run: make coverage

      # Upload a file
      - name: Upload coverage.info
        uses: actions/upload-artifact@v4
        with:
          name: coverage.info
          path: build/coverage/coverage.info
          # retention-days: 1 # Delete the file after 1 day
  
  # Job for the coverage of the code
  Codecov:
    needs: project-coverage
    name: Codecov
    runs-on: ubuntu-latest
    # container:
    #   image: debian:bookworm-slim
      
    steps:
      # - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.info
          token: ${{ secrets.CODECOV_TOKEN }}