name: run-tests
on:
  workflow_run:
    workflows: ["build-project"]
    types:
      - completed

jobs:
  tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # VM avec la dernière version de ubuntu
    runs-on: ubuntu-latest
    # Image (dans ce cas alpine version 3.19)
    container:
      image: bookworm-slim

    steps:
      # Récupère le code
      - name: get-code
        uses: actions/checkout@v4

      # Installation des packages manquant
      - name: install-packages
        # --no-cache limite l'utilisation de la mémoire
        # build-base installe les packages nécessaires (gcc, make, etc...)
        run: apt-get install -y --no-install-recommends \
          build-essential \
          check

      - name: run-tests
        run: make test