name: run-tests
on: [push, pull_request]
  # push:
  # pull_request:

jobs:
  tests:
    name: Perform tests
    # VM avec la dernière version de ubuntu
    runs-on: ubuntu-latest
    # Image (dans ce cas alpine version 3.19)
    container:
      image: debian:bookworm-slim

    steps:
      # Récupère le code
      - name: get-code
        uses: actions/checkout@v4

      # Installation des packages manquant
      - name: install-packages
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential \
            check

      # Lance le make pour les tests
      - name: run-tests
        run: make test

  linter:
    name: Linter
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim

    steps:
      - uses: actions/checkout@v4
      - name: install-packages
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential \
            check \
            clang-tidy

      - name: Run lint
        run: make lint

  format-check:
    name: Checks code format
    runs-on: ubuntu-latest
    container:
      image: debian:booksworm-slim

    steps:
      - uses: actions/chechout@v4
      - name: install-packages
        run: |
          apt-get upade
          apt-get install -y --no-install-recommends make clang-format

      - name: Run format check
        run: make format-check